/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela2.java
 *
 * Created on 16/04/2010, 19:41:51
 */

package View;

/**
 *
 * @author Leandro
 */
public class Tela2 extends javax.swing.JFrame {

    /** Creates new form Tela2 */
    public Tela2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPrincipal = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btBusca = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        lbCodUsuario = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbAcesso = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lbFuncao = new javax.swing.JLabel();
        lbTelCelular = new javax.swing.JLabel();
        lbTelResidencia = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        lbConfirmaSenha = new javax.swing.JLabel();
        txCodUsuario = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        cbAcesso = new javax.swing.JComboBox();
        txEndereco = new javax.swing.JTextField();
        txBairro = new javax.swing.JTextField();
        txCidade = new javax.swing.JTextField();
        txCpf = new javax.swing.JTextField();
        txFuncao = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        txUsuario = new javax.swing.JTextField();
        pwSenha = new javax.swing.JPasswordField();
        pwConfSenha = new javax.swing.JPasswordField();
        rbAtivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        txComplemento = new javax.swing.JTextField();
        lbUF = new javax.swing.JLabel();
        lbCEP = new javax.swing.JLabel();
        txUF = new javax.swing.JTextField();
        txCEP = new javax.swing.JTextField();
        txTelResidencial = new javax.swing.JTextField();
        txTelCelular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        tbPrincipal.setFloatable(false);
        tbPrincipal.setOrientation(1);
        tbPrincipal.setRollover(true);

        btNovo.setFont(new java.awt.Font("Tahoma", 0, 12));
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/novo.GIF"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setMaximumSize(new java.awt.Dimension(70, 41));
        btNovo.setMinimumSize(new java.awt.Dimension(70, 41));
        btNovo.setPreferredSize(new java.awt.Dimension(70, 41));
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPrincipal.add(btNovo);

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 12));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/salvar.GIF"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setMaximumSize(new java.awt.Dimension(70, 41));
        btSalvar.setMinimumSize(new java.awt.Dimension(70, 41));
        btSalvar.setPreferredSize(new java.awt.Dimension(70, 41));
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPrincipal.add(btSalvar);

        btBusca.setFont(new java.awt.Font("Tahoma", 0, 12));
        btBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/busca.gif"))); // NOI18N
        btBusca.setText("Busca");
        btBusca.setFocusable(false);
        btBusca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBusca.setMaximumSize(new java.awt.Dimension(70, 41));
        btBusca.setMinimumSize(new java.awt.Dimension(70, 41));
        btBusca.setPreferredSize(new java.awt.Dimension(70, 41));
        btBusca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPrincipal.add(btBusca);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 12));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/cancel.gif"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(70, 41));
        btCancelar.setMinimumSize(new java.awt.Dimension(70, 41));
        btCancelar.setPreferredSize(new java.awt.Dimension(70, 41));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPrincipal.add(btCancelar);

        btFechar.setFont(new java.awt.Font("Tahoma", 0, 12));
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/sair.GIF"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setFocusable(false);
        btFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFechar.setMaximumSize(new java.awt.Dimension(70, 41));
        btFechar.setMinimumSize(new java.awt.Dimension(70, 41));
        btFechar.setPreferredSize(new java.awt.Dimension(70, 41));
        btFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPrincipal.add(btFechar);

        getContentPane().add(tbPrincipal);
        tbPrincipal.setBounds(10, 11, 80, 292);

        lbCodUsuario.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbCodUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodUsuario.setText("Código do Usuário Nº");
        getContentPane().add(lbCodUsuario);
        lbCodUsuario.setBounds(100, 70, 150, 20);

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome.setText("Nome Completo:");
        getContentPane().add(lbNome);
        lbNome.setBounds(110, 99, 104, 17);

        lbAcesso.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbAcesso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAcesso.setText("Acesso:");
        getContentPane().add(lbAcesso);
        lbAcesso.setBounds(110, 129, 47, 17);

        lbEndereco.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEndereco.setText("Endereço:");
        getContentPane().add(lbEndereco);
        lbEndereco.setBounds(110, 160, 63, 17);

        lbBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBairro.setText("Bairro:");
        getContentPane().add(lbBairro);
        lbBairro.setBounds(320, 220, 40, 17);

        lbCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCidade.setText("Cidade:");
        getContentPane().add(lbCidade);
        lbCidade.setBounds(90, 220, 46, 17);

        lbCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCPF.setText("CPF:");
        getContentPane().add(lbCPF);
        lbCPF.setBounds(490, 70, 29, 17);

        lbFuncao.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbFuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFuncao.setText("Função:");
        getContentPane().add(lbFuncao);
        lbFuncao.setBounds(490, 100, 50, 17);

        lbTelCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTelCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTelCelular.setText("Tel Celular:");
        getContentPane().add(lbTelCelular);
        lbTelCelular.setBounds(500, 160, 66, 17);

        lbTelResidencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTelResidencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTelResidencia.setText("Tel Residencial:");
        getContentPane().add(lbTelResidencia);
        lbTelResidencia.setBounds(480, 130, 91, 17);

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmail.setText("E-mail:");
        getContentPane().add(lbEmail);
        lbEmail.setBounds(490, 190, 41, 17);

        lbUsuario.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario.setText("Usuário:");
        getContentPane().add(lbUsuario);
        lbUsuario.setBounds(390, 246, 50, 17);

        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSenha.setText("Senha:");
        getContentPane().add(lbSenha);
        lbSenha.setBounds(390, 270, 43, 17);

        lbConfirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbConfirmaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConfirmaSenha.setText("Confirmar Senha:");
        getContentPane().add(lbConfirmaSenha);
        lbConfirmaSenha.setBounds(330, 300, 107, 17);
        getContentPane().add(txCodUsuario);
        txCodUsuario.setBounds(250, 70, 140, 20);
        getContentPane().add(txNome);
        txNome.setBounds(220, 99, 227, 20);

        cbAcesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbAcesso);
        cbAcesso.setBounds(160, 129, 140, 20);
        getContentPane().add(txEndereco);
        txEndereco.setBounds(180, 160, 270, 20);
        getContentPane().add(txBairro);
        txBairro.setBounds(360, 220, 127, 20);
        getContentPane().add(txCidade);
        txCidade.setBounds(140, 220, 170, 20);
        getContentPane().add(txCpf);
        txCpf.setBounds(540, 70, 181, 20);
        getContentPane().add(txFuncao);
        txFuncao.setBounds(540, 100, 181, 20);

        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txEmail);
        txEmail.setBounds(540, 190, 190, 20);
        getContentPane().add(txUsuario);
        txUsuario.setBounds(440, 246, 140, 20);
        getContentPane().add(pwSenha);
        pwSenha.setBounds(440, 270, 140, 20);
        getContentPane().add(pwConfSenha);
        pwConfSenha.setBounds(440, 300, 140, 20);

        rbAtivo.setText("Ativo");
        getContentPane().add(rbAtivo);
        rbAtivo.setBounds(320, 129, 60, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Nº");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 190, 16, 17);
        getContentPane().add(txNum);
        txNum.setBounds(130, 190, 44, 20);

        lbComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbComplemento.setText("Complemento:");
        getContentPane().add(lbComplemento);
        lbComplemento.setBounds(190, 190, 91, 17);
        getContentPane().add(txComplemento);
        txComplemento.setBounds(290, 190, 90, 20);

        lbUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUF.setText("UF:");
        getContentPane().add(lbUF);
        lbUF.setBounds(390, 190, 21, 17);

        lbCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCEP.setText("CEP:");
        getContentPane().add(lbCEP);
        lbCEP.setBounds(90, 246, 30, 17);
        getContentPane().add(txUF);
        txUF.setBounds(412, 190, 49, 20);

        txCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCEPActionPerformed(evt);
            }
        });
        getContentPane().add(txCEP);
        txCEP.setBounds(120, 246, 150, 20);

        txTelResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelResidencialActionPerformed(evt);
            }
        });
        getContentPane().add(txTelResidencial);
        txTelResidencial.setBounds(590, 130, 140, 20);

        txTelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelCelularActionPerformed(evt);
            }
        });
        getContentPane().add(txTelCelular);
        txTelCelular.setBounds(590, 160, 140, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("USUARIO DO SISTEMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 20, 210, 22);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Acesso"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setPreferredSize(new java.awt.Dimension(800, 64));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 420, 740, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txTelResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelResidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelResidencialActionPerformed

    private void txTelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelCelularActionPerformed

    private void txCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCEPActionPerformed

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAcesso;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCEP;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCodUsuario;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbConfirmaSenha;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbFuncao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTelCelular;
    private javax.swing.JLabel lbTelResidencia;
    private javax.swing.JLabel lbUF;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField pwConfSenha;
    private javax.swing.JPasswordField pwSenha;
    private javax.swing.JRadioButton rbAtivo;
    private javax.swing.JToolBar tbPrincipal;
    private javax.swing.JTextField txBairro;
    private javax.swing.JTextField txCEP;
    private javax.swing.JTextField txCidade;
    private javax.swing.JTextField txCodUsuario;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JTextField txCpf;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txEndereco;
    private javax.swing.JTextField txFuncao;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNum;
    private javax.swing.JTextField txTelCelular;
    private javax.swing.JTextField txTelResidencial;
    private javax.swing.JTextField txUF;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables

}
