/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaAberturaOS.java
 *
 * Created on 17/04/2010, 23:13:01
 */

package View;

/**
 *
 * @author Administrador
 */
public class TelaCadUsuario extends javax.swing.JFrame {

    /** Creates new form TelaAberturaOS */
    public TelaCadUsuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        lbTituloAbre = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        spTabela = new javax.swing.JScrollPane();
        tbTabela = new javax.swing.JTable();
        tbAbertura = new javax.swing.JToolBar();
        btAbrirOS = new javax.swing.JButton();
        btFecharOS = new javax.swing.JButton();
        btSalvarOS = new javax.swing.JButton();
        btLimparOS = new javax.swing.JButton();
        btImpOS = new javax.swing.JButton();
        btEmailOS = new javax.swing.JButton();
        btCancelarOS = new javax.swing.JButton();
        btFecharAberOS = new javax.swing.JButton();
        pbStatusAbert = new javax.swing.JProgressBar();
        jTFNome = new javax.swing.JTextField();
        LBEnde = new javax.swing.JLabel();
        TFEnde = new javax.swing.JTextField();
        LBBairro = new javax.swing.JLabel();
        TFBairro = new javax.swing.JTextField();
        lBCidade = new javax.swing.JLabel();
        TFCidade = new javax.swing.JTextField();
        LBFunc = new javax.swing.JLabel();
        LBOutros = new javax.swing.JLabel();
        TFOutros = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LBCEP = new javax.swing.JLabel();
        TFCEP = new javax.swing.JTextField();
        LBUF = new javax.swing.JLabel();
        CBUF = new javax.swing.JComboBox();
        LBCPF = new javax.swing.JLabel();
        TFCPF = new javax.swing.JTextField();
        LBFone = new javax.swing.JLabel();
        LBFoneComer = new javax.swing.JLabel();
        TFFone = new javax.swing.JTextField();
        TFFoneComer = new javax.swing.JTextField();
        BTFunc = new javax.swing.JButton();
        CBFunc = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abertura de Ordem de Serviço");
        setBounds(new java.awt.Rectangle(10, 10, 800, 600));
        setMinimumSize(new java.awt.Dimension(900, 700));

        lbNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNome.setText("Nome:");
        lbNome.setAutoscrolls(true);

        lbTituloAbre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTituloAbre.setText("Cadastro de Usuário");
        lbTituloAbre.setAutoscrolls(true);

        lbNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNum.setText("Codigo do Usuário:");
        lbNum.setAutoscrolls(true);

        spTabela.setAutoscrolls(true);

        tbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Em estoque", "R$", "Qtd", "Total"
            }
        ));
        spTabela.setViewportView(tbTabela);

        tbAbertura.setFloatable(false);
        tbAbertura.setOrientation(1);
        tbAbertura.setRollover(true);
        tbAbertura.setAutoscrolls(true);
        tbAbertura.setMaximumSize(new java.awt.Dimension(100, 60));
        tbAbertura.setMinimumSize(new java.awt.Dimension(100, 60));
        tbAbertura.setPreferredSize(new java.awt.Dimension(100, 60));

        btAbrirOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/novo.png"))); // NOI18N
        btAbrirOS.setText("Novo");
        btAbrirOS.setFocusable(false);
        btAbrirOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAbrirOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btAbrirOS);

        btFecharOS.setFont(new java.awt.Font("Tahoma", 1, 10));
        btFecharOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar.png"))); // NOI18N
        btFecharOS.setText("Excluir");
        btFecharOS.setFocusable(false);
        btFecharOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btFecharOS);

        btSalvarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Salvar.png"))); // NOI18N
        btSalvarOS.setText("Salvar");
        btSalvarOS.setFocusable(false);
        btSalvarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btSalvarOS);

        btLimparOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/limpar.png"))); // NOI18N
        btLimparOS.setText("Limpar");
        btLimparOS.setFocusable(false);
        btLimparOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimparOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btLimparOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btLimparOS);

        btImpOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/imprimir.png"))); // NOI18N
        btImpOS.setText("Imprimir");
        btImpOS.setFocusable(false);
        btImpOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImpOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btImpOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btImpOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btImpOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btImpOS);

        btEmailOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/email.png"))); // NOI18N
        btEmailOS.setText("E-mail");
        btEmailOS.setFocusable(false);
        btEmailOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmailOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btEmailOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btEmailOS);

        btCancelarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Cancelar.png"))); // NOI18N
        btCancelarOS.setText("Cancelar");
        btCancelarOS.setFocusable(false);
        btCancelarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btCancelarOS);

        btFecharAberOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar2.png"))); // NOI18N
        btFecharAberOS.setText("Fechar");
        btFecharAberOS.setFocusable(false);
        btFecharAberOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharAberOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbertura.add(btFecharAberOS);

        pbStatusAbert.setAutoscrolls(true);

        LBEnde.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBEnde.setText("Emdereço:");

        LBBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBBairro.setText("Bairro:");

        lBCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lBCidade.setText("Cidade:");

        LBFunc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBFunc.setText("Função:");

        LBOutros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBOutros.setText("Outros:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LBCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBCEP.setText("CEP:");

        LBUF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBUF.setText("UF:");

        CBUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LBCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBCPF.setText("CPF:");

        LBFone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBFone.setText("Telefone :");

        LBFoneComer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBFoneComer.setText("Telefone Comercial:");

        BTFunc.setText("...");

        CBFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbStatusAbert, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBOutros)
                                .addGap(33, 33, 33)
                                .addComponent(TFOutros, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
                            .addComponent(spTabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lbNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                                .addComponent(lbTituloAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBEnde)
                                    .addComponent(LBBairro)
                                    .addComponent(lBCidade)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LBCPF)
                                        .addComponent(LBFunc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbNome)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFEnde, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                                            .addComponent(TFBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBUF)
                                                .addGap(18, 18, 18)
                                                .addComponent(CBUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBCEP)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BTFunc)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBFoneComer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addComponent(LBFone))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFFone)
                                            .addComponent(TFFoneComer, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                                    .addComponent(jTFNome, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTituloAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNum)
                            .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBEnde)
                                    .addComponent(TFEnde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBBairro)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBCEP)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lBCidade)
                                        .addComponent(TFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LBUF)
                                    .addComponent(CBUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(TFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LBFone)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBFoneComer)
                                            .addComponent(TFFoneComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBCPF)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BTFunc)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(spTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LBOutros)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addComponent(pbStatusAbert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFuncActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAberturaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFunc;
    private javax.swing.JComboBox CBFunc;
    private javax.swing.JComboBox CBUF;
    private javax.swing.JLabel LBBairro;
    private javax.swing.JLabel LBCEP;
    private javax.swing.JLabel LBCPF;
    private javax.swing.JLabel LBEnde;
    private javax.swing.JLabel LBFone;
    private javax.swing.JLabel LBFoneComer;
    private javax.swing.JLabel LBFunc;
    private javax.swing.JLabel LBOutros;
    private javax.swing.JLabel LBUF;
    private javax.swing.JTextField TFBairro;
    private javax.swing.JTextField TFCEP;
    private javax.swing.JTextField TFCPF;
    private javax.swing.JTextField TFCidade;
    private javax.swing.JTextField TFEnde;
    private javax.swing.JTextField TFFone;
    private javax.swing.JTextField TFFoneComer;
    private javax.swing.JTextField TFOutros;
    private javax.swing.JButton btAbrirOS;
    private javax.swing.JButton btCancelarOS;
    private javax.swing.JButton btEmailOS;
    private javax.swing.JButton btFecharAberOS;
    private javax.swing.JButton btFecharOS;
    private javax.swing.JButton btImpOS;
    private javax.swing.JButton btLimparOS;
    private javax.swing.JButton btSalvarOS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JLabel lBCidade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbTituloAbre;
    private javax.swing.JProgressBar pbStatusAbert;
    private javax.swing.JScrollPane spTabela;
    private javax.swing.JToolBar tbAbertura;
    private javax.swing.JTable tbTabela;
    private javax.swing.JTextField txNum;
    // End of variables declaration//GEN-END:variables

}
