/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaAberturaOS.java
 *
 * Created on 17/04/2010, 23:13:01
 */

package View;

/**
 *
 * @author Administrador
 */
public class TelaAberturaOS extends javax.swing.JFrame {

    /** Creates new form TelaAberturaOS */
    public TelaAberturaOS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAtendente = new javax.swing.JComboBox();
        lbAtendente = new javax.swing.JLabel();
        lbTecnico = new javax.swing.JLabel();
        cbTecnico = new javax.swing.JComboBox();
        lbTituloAbreOS = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        btBuscaClienteOS = new javax.swing.JButton();
        btNovoClienteOS = new javax.swing.JButton();
        spDescricaoOS = new javax.swing.JScrollPane();
        taDescricaoOS = new javax.swing.JTextArea();
        lbDataOS = new javax.swing.JLabel();
        txDataOS = new javax.swing.JTextField();
        lbHoraOS = new javax.swing.JLabel();
        txHoraOS = new javax.swing.JTextField();
        lbDescricaoOS = new javax.swing.JLabel();
        lbNumOS = new javax.swing.JLabel();
        txNumOS = new javax.swing.JTextField();
        lbDescontoOS = new javax.swing.JLabel();
        txDescontoOS = new javax.swing.JTextField();
        lbTotalOS = new javax.swing.JLabel();
        txTotalOS = new javax.swing.JTextField();
        spItemOS = new javax.swing.JScrollPane();
        tbItemOS = new javax.swing.JTable();
        tbAberturaOS = new javax.swing.JToolBar();
        btAbrirOS = new javax.swing.JButton();
        btFecharOS = new javax.swing.JButton();
        btSalvarOS = new javax.swing.JButton();
        btLimparOS = new javax.swing.JButton();
        btImpOS = new javax.swing.JButton();
        btEmailOS = new javax.swing.JButton();
        btCancelarOS = new javax.swing.JButton();
        btFecharAberOS = new javax.swing.JButton();
        pbStatusAbertOS = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abertura de Ordem de Serviço");
        setBounds(new java.awt.Rectangle(10, 10, 800, 600));
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        cbAtendente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAtendente.setAutoscrolls(true);
        getContentPane().add(cbAtendente);
        cbAtendente.setBounds(90, 117, 226, 20);

        lbAtendente.setFont(new java.awt.Font("Arial", 0, 14));
        lbAtendente.setText("Atendente:");
        lbAtendente.setAutoscrolls(true);
        getContentPane().add(lbAtendente);
        lbAtendente.setBounds(90, 94, 69, 17);

        lbTecnico.setFont(new java.awt.Font("Arial", 0, 14));
        lbTecnico.setText("Técnico:");
        lbTecnico.setAutoscrolls(true);
        getContentPane().add(lbTecnico);
        lbTecnico.setBounds(380, 94, 54, 17);

        cbTecnico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTecnico.setAutoscrolls(true);
        getContentPane().add(cbTecnico);
        cbTecnico.setBounds(380, 117, 226, 20);

        lbTituloAbreOS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTituloAbreOS.setText("Controle de Ordem de Serviço");
        lbTituloAbreOS.setAutoscrolls(true);
        getContentPane().add(lbTituloAbreOS);
        lbTituloAbreOS.setBounds(560, 10, 215, 36);

        lbCliente.setFont(new java.awt.Font("Arial", 0, 14));
        lbCliente.setText("Cliente:");
        lbCliente.setAutoscrolls(true);
        getContentPane().add(lbCliente);
        lbCliente.setBounds(90, 147, 48, 17);

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCliente.setAutoscrolls(true);
        getContentPane().add(cbCliente);
        cbCliente.setBounds(90, 180, 353, 22);

        btBuscaClienteOS.setText("Busca");
        btBuscaClienteOS.setAutoscrolls(true);
        getContentPane().add(btBuscaClienteOS);
        btBuscaClienteOS.setBounds(460, 180, 61, 23);

        btNovoClienteOS.setText("Novo");
        btNovoClienteOS.setAutoscrolls(true);
        getContentPane().add(btNovoClienteOS);
        btNovoClienteOS.setBounds(528, 180, 61, 23);

        spDescricaoOS.setAutoscrolls(true);

        taDescricaoOS.setColumns(20);
        taDescricaoOS.setRows(5);
        spDescricaoOS.setViewportView(taDescricaoOS);

        getContentPane().add(spDescricaoOS);
        spDescricaoOS.setBounds(90, 244, 504, 103);

        lbDataOS.setFont(new java.awt.Font("Arial", 0, 14));
        lbDataOS.setText("Data Abertura:");
        lbDataOS.setAutoscrolls(true);
        getContentPane().add(lbDataOS);
        lbDataOS.setBounds(616, 244, 93, 17);
        getContentPane().add(txDataOS);
        txDataOS.setBounds(616, 267, 123, 20);

        lbHoraOS.setFont(new java.awt.Font("Arial", 0, 14));
        lbHoraOS.setText("Hora de Abertura");
        lbHoraOS.setAutoscrolls(true);
        getContentPane().add(lbHoraOS);
        lbHoraOS.setBounds(616, 293, 109, 17);
        getContentPane().add(txHoraOS);
        txHoraOS.setBounds(620, 320, 123, 20);

        lbDescricaoOS.setFont(new java.awt.Font("Arial", 0, 14));
        lbDescricaoOS.setText("Descrição:");
        lbDescricaoOS.setAutoscrolls(true);
        getContentPane().add(lbDescricaoOS);
        lbDescricaoOS.setBounds(90, 221, 67, 17);

        lbNumOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNumOS.setText("Nº O.S.");
        lbNumOS.setAutoscrolls(true);
        getContentPane().add(lbNumOS);
        lbNumOS.setBounds(90, 51, 46, 17);
        getContentPane().add(txNumOS);
        txNumOS.setBounds(154, 48, 69, 20);

        lbDescontoOS.setFont(new java.awt.Font("Arial", 0, 14));
        lbDescontoOS.setText("Desconto:");
        lbDescontoOS.setAutoscrolls(true);
        getContentPane().add(lbDescontoOS);
        lbDescontoOS.setBounds(547, 477, 90, 17);
        getContentPane().add(txDescontoOS);
        txDescontoOS.setBounds(547, 510, 97, 20);

        lbTotalOS.setFont(new java.awt.Font("Arial", 0, 14));
        lbTotalOS.setText("Total a Pagar:");
        lbTotalOS.setAutoscrolls(true);
        getContentPane().add(lbTotalOS);
        lbTotalOS.setBounds(657, 477, 90, 17);
        getContentPane().add(txTotalOS);
        txTotalOS.setBounds(657, 510, 97, 20);

        spItemOS.setAutoscrolls(true);

        tbItemOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Descrição", "Em estoque", "R$", "Qtd", "Total"
            }
        ));
        spItemOS.setViewportView(tbItemOS);

        getContentPane().add(spItemOS);
        spItemOS.setBounds(90, 365, 664, 94);

        tbAberturaOS.setFloatable(false);
        tbAberturaOS.setOrientation(1);
        tbAberturaOS.setRollover(true);
        tbAberturaOS.setAutoscrolls(true);
        tbAberturaOS.setMaximumSize(new java.awt.Dimension(100, 60));
        tbAberturaOS.setMinimumSize(new java.awt.Dimension(100, 60));
        tbAberturaOS.setPreferredSize(new java.awt.Dimension(100, 60));

        btAbrirOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/novo.png"))); // NOI18N
        btAbrirOS.setText("Abrir OS");
        btAbrirOS.setFocusable(false);
        btAbrirOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAbrirOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btAbrirOS);

        btFecharOS.setFont(new java.awt.Font("Tahoma", 1, 10));
        btFecharOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar.png"))); // NOI18N
        btFecharOS.setText("Fechar OS");
        btFecharOS.setFocusable(false);
        btFecharOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btFecharOS);

        btSalvarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Salvar.png"))); // NOI18N
        btSalvarOS.setText("Salvar");
        btSalvarOS.setFocusable(false);
        btSalvarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btSalvarOS);

        btLimparOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/limpar.png"))); // NOI18N
        btLimparOS.setText("Limpar");
        btLimparOS.setFocusable(false);
        btLimparOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimparOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btLimparOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btLimparOS);

        btImpOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/imprimir.png"))); // NOI18N
        btImpOS.setText("Imprimir");
        btImpOS.setFocusable(false);
        btImpOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImpOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btImpOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btImpOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btImpOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btImpOS);

        btEmailOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/email.png"))); // NOI18N
        btEmailOS.setText("E-mail");
        btEmailOS.setFocusable(false);
        btEmailOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmailOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btEmailOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btEmailOS);

        btCancelarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Cancelar.png"))); // NOI18N
        btCancelarOS.setText("Cancelar");
        btCancelarOS.setFocusable(false);
        btCancelarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btCancelarOS);

        btFecharAberOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar2.png"))); // NOI18N
        btFecharAberOS.setText("Fechar");
        btFecharAberOS.setFocusable(false);
        btFecharAberOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharAberOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btFecharAberOS);

        getContentPane().add(tbAberturaOS);
        tbAberturaOS.setBounds(0, 0, 72, 572);

        pbStatusAbertOS.setAutoscrolls(true);
        getContentPane().add(pbStatusAbertOS);
        pbStatusAbertOS.setBounds(60, 580, 700, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(597, 244, 1, 115);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAberturaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirOS;
    private javax.swing.JButton btBuscaClienteOS;
    private javax.swing.JButton btCancelarOS;
    private javax.swing.JButton btEmailOS;
    private javax.swing.JButton btFecharAberOS;
    private javax.swing.JButton btFecharOS;
    private javax.swing.JButton btImpOS;
    private javax.swing.JButton btLimparOS;
    private javax.swing.JButton btNovoClienteOS;
    private javax.swing.JButton btSalvarOS;
    private javax.swing.JComboBox cbAtendente;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbTecnico;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAtendente;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDataOS;
    private javax.swing.JLabel lbDescontoOS;
    private javax.swing.JLabel lbDescricaoOS;
    private javax.swing.JLabel lbHoraOS;
    private javax.swing.JLabel lbNumOS;
    private javax.swing.JLabel lbTecnico;
    private javax.swing.JLabel lbTituloAbreOS;
    private javax.swing.JLabel lbTotalOS;
    private javax.swing.JProgressBar pbStatusAbertOS;
    private javax.swing.JScrollPane spDescricaoOS;
    private javax.swing.JScrollPane spItemOS;
    private javax.swing.JTextArea taDescricaoOS;
    private javax.swing.JToolBar tbAberturaOS;
    private javax.swing.JTable tbItemOS;
    private javax.swing.JTextField txDataOS;
    private javax.swing.JTextField txDescontoOS;
    private javax.swing.JTextField txHoraOS;
    private javax.swing.JTextField txNumOS;
    private javax.swing.JTextField txTotalOS;
    // End of variables declaration//GEN-END:variables

}
