/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaAberturaOS.java
 *
 * Created on 17/04/2010, 23:13:01
 */

package View;

/**
 *
 * @author Administrador
 */
public class TelaCadFonecedor extends javax.swing.JFrame {

    /** Creates new form TelaAberturaOS */
    public TelaCadFonecedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAtendente = new javax.swing.JLabel();
        lbTituloAbreOS = new javax.swing.JLabel();
        lbNumOS = new javax.swing.JLabel();
        txNumOS = new javax.swing.JTextField();
        spItemOS = new javax.swing.JScrollPane();
        tbItemOS = new javax.swing.JTable();
        tbAberturaOS = new javax.swing.JToolBar();
        btAbrirOS = new javax.swing.JButton();
        btFecharOS = new javax.swing.JButton();
        btSalvarOS = new javax.swing.JButton();
        btLimparOS = new javax.swing.JButton();
        btImpOS = new javax.swing.JButton();
        btEmailOS = new javax.swing.JButton();
        btCancelarOS = new javax.swing.JButton();
        btFecharAberOS = new javax.swing.JButton();
        pbStatusAbertOS = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abertura de Ordem de Serviço");
        setBounds(new java.awt.Rectangle(10, 10, 800, 600));
        setMinimumSize(new java.awt.Dimension(900, 700));

        lbAtendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbAtendente.setText("Empresa:");
        lbAtendente.setAutoscrolls(true);

        lbTituloAbreOS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTituloAbreOS.setText("Cadastro de Fornecedor");
        lbTituloAbreOS.setAutoscrolls(true);

        lbNumOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNumOS.setText("Codigo do Fornecedor:");
        lbNumOS.setAutoscrolls(true);

        spItemOS.setAutoscrolls(true);

        tbItemOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Descrição", "Em estoque", "R$", "Qtd", "Total"
            }
        ));
        spItemOS.setViewportView(tbItemOS);

        tbAberturaOS.setFloatable(false);
        tbAberturaOS.setOrientation(1);
        tbAberturaOS.setRollover(true);
        tbAberturaOS.setAutoscrolls(true);
        tbAberturaOS.setMaximumSize(new java.awt.Dimension(100, 60));
        tbAberturaOS.setMinimumSize(new java.awt.Dimension(100, 60));
        tbAberturaOS.setPreferredSize(new java.awt.Dimension(100, 60));

        btAbrirOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/novo.png"))); // NOI18N
        btAbrirOS.setText("Novo");
        btAbrirOS.setFocusable(false);
        btAbrirOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAbrirOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btAbrirOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btAbrirOS);

        btFecharOS.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFecharOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar.png"))); // NOI18N
        btFecharOS.setText("Excluir");
        btFecharOS.setFocusable(false);
        btFecharOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btFecharOS);

        btSalvarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Salvar.png"))); // NOI18N
        btSalvarOS.setText("Salvar");
        btSalvarOS.setFocusable(false);
        btSalvarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btSalvarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btSalvarOS);

        btLimparOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/limpar.png"))); // NOI18N
        btLimparOS.setText("Limpar");
        btLimparOS.setFocusable(false);
        btLimparOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimparOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btLimparOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btLimparOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btLimparOS);

        btImpOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/imprimir.png"))); // NOI18N
        btImpOS.setText("Imprimir");
        btImpOS.setFocusable(false);
        btImpOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImpOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btImpOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btImpOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btImpOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btImpOS);

        btEmailOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/email.png"))); // NOI18N
        btEmailOS.setText("E-mail");
        btEmailOS.setFocusable(false);
        btEmailOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmailOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btEmailOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btEmailOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btEmailOS);

        btCancelarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Cancelar.png"))); // NOI18N
        btCancelarOS.setText("Cancelar");
        btCancelarOS.setFocusable(false);
        btCancelarOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelarOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btCancelarOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btCancelarOS);

        btFecharAberOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Fechar2.png"))); // NOI18N
        btFecharAberOS.setText("Fechar");
        btFecharAberOS.setFocusable(false);
        btFecharAberOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharAberOS.setMaximumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setMinimumSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setPreferredSize(new java.awt.Dimension(70, 70));
        btFecharAberOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAberturaOS.add(btFecharAberOS);

        pbStatusAbertOS.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Contato:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Emdereço:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Bairro:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Cidade:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Ramo:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Outros:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("UF:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("CNPJ:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Telefone Comercial:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Telefone Comercial:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Fax:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbAberturaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbStatusAbertOS, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                            .addComponent(spItemOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAtendente)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbNumOS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txNumOS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                                        .addComponent(lbTituloAbreOS, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField12)
                                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField10)))))))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAberturaOS, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTituloAbreOS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNumOS)
                            .addComponent(txNumOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAtendente)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(spItemOS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbStatusAbertOS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAberturaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirOS;
    private javax.swing.JButton btCancelarOS;
    private javax.swing.JButton btEmailOS;
    private javax.swing.JButton btFecharAberOS;
    private javax.swing.JButton btFecharOS;
    private javax.swing.JButton btImpOS;
    private javax.swing.JButton btLimparOS;
    private javax.swing.JButton btSalvarOS;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbAtendente;
    private javax.swing.JLabel lbNumOS;
    private javax.swing.JLabel lbTituloAbreOS;
    private javax.swing.JProgressBar pbStatusAbertOS;
    private javax.swing.JScrollPane spItemOS;
    private javax.swing.JToolBar tbAberturaOS;
    private javax.swing.JTable tbItemOS;
    private javax.swing.JTextField txNumOS;
    // End of variables declaration//GEN-END:variables

}
